/**
 * Poetic introductions for each inspiration's gallery page.
 * Keyed by slug (from toSlug() in gallery-filters.ts).
 */
export const inspirationIntros: Record<string, string> = {
	// Musicians
	'sabrina-carpenter':
		'Sabrina Carpenter wraps retro-pop sweetness around something sharper, like a pastel candy with a bitter center. Her songs channel 1960s girl-group harmonics filtered through modern irreverence, every wink loaded with double meaning. "Espresso" loops in your head the way a neon sign buzzes: persistent, warm, slightly dangerous. Picture hot pink gradients bleeding into deep mauve, glitter particles drifting over a dark coral backdrop.',
	'laufey':
		'Laufey inhabits the golden stillness between a jazz standard and a lullaby. Her voice carries the texture of velvet draped over old wood, each note placed with the care of someone arranging flowers in a room no one else will see. Songs like "From the Start" feel like rediscovering a handwritten letter tucked inside a library book. Warm ivory, antique gold, and the soft amber of afternoon light through linen curtains.',
	'dua-lipa':
		'Dua Lipa builds pop music like architecture: load-bearing basslines, mirrored surfaces, nothing wasted. "Levitating" and "Don\'t Start Now" are disco blueprints engineered for maximum kinetic force, every beat placement deliberate as a strobe flash. She makes relentlessness feel effortless, cool radiating outward like heat from polished chrome. Electric magenta, deep cobalt, and silver pulses against black.',
	'billie-eilish':
		'Billie Eilish occupies the space between a whisper and a scream, building whole worlds from ASMR-close vocals and subterranean bass. "Bury a Friend" turns negative space into architecture; "What Was I Made For?" strips everything back to a single aching frequency. Her music feels like watching fog roll through an empty parking garage at midnight. Pale green bioluminescence, deep shadow, desaturated lavender fading into black.',
	'taylor-swift':
		'Taylor Swift keeps a living archive of selves, each album era its own distinct world with its own color theory and emotional weather. From the Nashville twang of her debut to the synth-pop reinvention of 1989 to the folklore woodlands, she treats autobiography as world-building. Every lyric is a precisely placed detail in an expanding mythology. Shifting palettes of midnight blue, autumn gold, silver glitter, and deep woodland green.',
	'beyonce':
		'Beyonce radiates omnidirectionally. From the Coachella marching band spectacle to the country-soul pivot of Cowboy Carter, she treats genre as raw material and performance as total transformation. Her discipline is architectural; her presence, solar. Even a single held note from "Love on Top" can reorganize a room. Deep gold, cathedral white, burnt sienna, and royal purple against infinite black.',
	'bad-bunny':
		'Bad Bunny refracts reggaeton through a funhouse mirror, turning machismo inside out and making vulnerability sound like the hardest flex on the block. "Yo Perreo Sola" is gender performance as dance floor thesis; Un Verano Sin Ti made an entire summer feel like a Caribbean daydream dissolving at the edges. He treats genre boundaries the way he treats fashion rules: as suggestions. Electric lime, sunset coral, deep violet, and tropical turquoise over asphalt gray.',
	'sza':
		'SZA lives in a golden hour that never fully resolves, her music suspended in the hazy stretch between longing and letting go. "Kill Bill" pivots from tenderness to menace mid-verse; "Normal Girl" aches with the specific pain of wanting simplicity from a complicated heart. Her vocals drift and spiral like smoke caught in warm light. Amber, burnt orange, soft sage green, and dusky rose over deep indigo.',
	'rihanna':
		'Rihanna bends the boundary between pop icon and cultural force so thoroughly that the distinction stopped mattering years ago. She gave us "Umbrella" and Fenty Beauty with the same imperial confidence, turning every platform into a runway and every runway into a statement. Even her silence (seven years without an album) became its own kind of presence. Deep ruby, molten gold, obsidian black, and flashes of electric tangerine.',
	'lady-gaga':
		'Lady Gaga treats metamorphosis as her primary medium, each era a complete becoming. The meat dress, the jazz duets with Tony Bennett, the stripped-back "Joanne" piano ballads, the Chromatica rave: none of these are contradictions. They are all load-bearing walls in an architecture of perpetual reinvention. Chrome silver, deep fuchsia, holographic iridescence, and bone white shifting across black.',
	'bruno-mars':
		'Bruno Mars is a jukebox prodigy who channels 24-karat nostalgia without a trace of irony. He pulls from Motown, New Jack Swing, and 80s funk with the easy precision of someone who learned these languages as a first tongue. "Uptown Funk" and "That\'s What I Like" land like songs that have always existed, discovered rather than written. Polished gold, cherry red, deep mahogany, and crisp white against black satin.',
	'the-weeknd':
		'The Weeknd soundtracks neon loneliness, capturing the seductive emptiness of a city at 3 AM when every light is on but nobody is home. "Blinding Lights" turns synthwave yearning into a full-speed chase through rain-slicked streets; "After Hours" bleeds with a glamour that knows exactly how hollow it is. His music makes isolation feel cinematic, almost beautiful. Deep crimson, electric blue, sodium-vapor amber, and cold white against endless black.',
	'ariana-grande':
		'Ariana Grande exists in a world of impossible smoothness: porcelain surfaces, liquid eyeliner arcs, ponytails pulled into architectural tension. Her vocal runs on "Dangerous Woman" and "Into You" move like light through fiber optic cable, bending without ever breaking. Even her whistle tones feel polished to a mirror finish. Gradients of soft mauve bleeding into pearl white, with thin glassy filaments catching light against deep, powdery black.',
	'chappell-roan':
		'Chappell Roan is a fever dream in drag makeup and Midwest sincerity, supercharged with queer maximalism. "Good Luck, Babe!" builds from a whispered confession into a neon cathedral of longing, and her live shows play like a county fair designed by a drag mother with an unlimited rhinestone budget. She makes spectacle feel deeply personal. Saturated hot pinks clashing against lime greens, glitter-gold accents, black eyeliner edges, and the deep red of a theatrical curtain.',
	'olivia-rodrigo':
		'Olivia Rodrigo captures the crystallized intensity of feeling everything at maximum volume for the very first time. "drivers license" turned a suburban parking lot into a cathedral of heartbreak, while "brutal" and "vampire" channel teen fury into tight, propulsive pop-punk architecture. She writes with the specificity of a diary entry and delivers with the force of a stadium anthem. Deep burgundy, ultraviolet purple, hot pink bleeding into black, and the cool blue-white glow of a phone screen illuminating tears at 2 AM.',
	'harry-styles':
		'Harry Styles is a kaleidoscope in gentle perpetual rotation, every turn revealing a new configuration of color, era, and self-expression. From One Direction pop to the psychedelic folk of Fine Line to the art deco world of "As It Was," he treats genre and gender as spectrums to explore rather than boxes to inhabit. His Gucci-meets-Bowie-meets-Laurel-Canyon wardrobe makes fashion feel like play rather than performance. Lavender, soft pink, rich chocolate brown, seafoam green, and the warm peach of golden hour light on vintage film stock.',

	// Actors
	'jim-carrey':
		'Jim Carrey is pure kinetic disruption, a human special effect whose face bends reality on a frame-by-frame basis. Watch The Mask or his Fire Marshall Bill sketches and you see flesh performing the work of animation cels. His pivot into painting revealed the same energy in looser form: wild acrylics, enormous gestures, nothing held back. Electric lime and hot yellow smearing across the canvas, with rubber-band distortion waves rippling through a field of manic, saturated primaries.',
	'jack-black':
		'Jack Black is volcanic joy, a round and irrepressible force whose energy predates irony. The power slides in "Tribute" with Tenacious D are performed with absolute commitment to absurdity, and his turn in School of Rock vibrates with genuine reverence for the loud guitar. He sweats enthusiasm. Molten orange erupting through cracked obsidian, heavy bass-frequency reds, warm spotlight gold, and the deep black of a cranked Marshall amp.',
	'robert-downey-jr':
		'Robert Downey Jr. carries the glint of machined titanium beneath a wisecrack. His Tony Stark layered narcissism over vulnerability so precisely that the seams never showed, and his Chaplin biopic proved the calibration runs deeper than quips. Every gesture is engineered to look effortless. Brushed gunmetal and polished chrome, accented with arc-reactor blue, deep burgundy leather, and the warm amber glow of old scotch in a glass.',
	'meryl-streep':
		'Meryl Streep dissolves into roles so completely that the craft becomes invisible. From the frozen precision of Miranda Priestly to the ragged warmth of Julia Child in Julie & Julia, she makes transformation look like breathing. Six decades of work and the instrument only grows more supple. Cool silver and slate layered with deep garnet, translucent washes of emotion bleeding through a surface of absolute technical control.',
	'anne-hathaway':
		'Anne Hathaway radiates the energy of transformation itself, the wide-eyed girl from The Princess Diaries who became the desperate Fantine shearing her hair in Les Mis. She commits to vulnerability with an almost alarming totality. Even her comedic timing in The Devil Wears Prada carries a current of genuine hunger underneath the charm. Crystalline whites shifting into deep rose, with sharp geometric facets refracting warm champagne light against cool midnight blue.',
	'zendaya':
		'Zendaya treats every red carpet appearance like an architectural statement, from the Joan of Arc Mugler armor to the Dune premiere where she became the sand itself. Her Rue in Euphoria vibrates between fragility and ferocity with no wasted motion. She selects collaborators (Valentino, Loewe, Jacquemus) the way a colorist selects pigments: deliberately. Deep bronze and warm copper against stark white, cool violet, and the precise gleam of polished onyx.',
	'keanu-reeves':
		'Keanu Reeves exists in a space between stillness and velocity, the calm center of a hurricane of motion. From the bullet-time freeze of Neo to the relentless forward momentum of John Wick, he embodies control under impossible pressure. There is something monastic about his screen presence: a quiet that feels earned, not performed. Midnight blacks and the cold blue trails of gunfire, punctuated by brief flares of warm neon bleeding through rain.',
	'pedro-pascal':
		'Pedro Pascal radiates the warmth of a story told around a fire, weathered and generous in equal measure. Behind the Mandalorian helmet or across the dining table in The Last of Us, he communicates tenderness through the smallest gestures. His presence carries the weight of someone who has survived enough to find gentleness revolutionary. Desert amber, terracotta, and deep burgundy: colors that feel like late sun on old adobe walls.',
	'ryan-gosling':
		'Ryan Gosling operates in the uncanny valley between cool detachment and devastating tenderness. He can be the silent, scorpion-jacketed driver or the lovesick dreamer at the piano in La La Land, and both versions feel true. There is a deliberate blankness to his surface that makes every crack in the facade seismic. Los Angeles at dusk: saturated pinks and electric blues dissolving into the soft grain of analog twilight.',
	'margot-robbie':
		'Margot Robbie is sunlight weaponized, blonde luminosity paired with a wicked, knowing edge. She turned Harley Quinn into a neon-smeared icon and played Barbie as both plastic perfection and existential crisis without breaking a sweat. Underneath the golden surface, there is always something sharper at work, a performer who uses beauty as misdirection. Bubblegum pink, molten gold, and the dangerous red of a lit fuse against glossy white.',
	'cate-blanchett':
		'Cate Blanchett is elemental, existing at the precise temperature of light itself. She inhabited Galadriel as something beyond human and played Bob Dylan as something beyond gender, always finding the frequency where performance becomes transfiguration. Every role she takes feels sculpted from a material the audience cannot quite name. Silver, pale opal, and the blue-white intensity of a star seen through winter atmosphere.',
	'jenna-ortega':
		'Jenna Ortega is precision dipped in shadow, a dark-eyed stillness that cuts through every frame she inhabits. As Wednesday Addams, she turned deadpan into a kind of superpower, each micro-expression calibrated to devastating effect. She belongs to a lineage of performers who understand that withholding can be more powerful than giving everything. Obsidian and deep plum, accented by the cold silver of moonlight on still water.',
	'ana-de-armas':
		'Ana de Armas carries a duality of classic Old Hollywood glamour and modern razor-sharp intensity. She radiates warm Mediterranean sensuality, all Cuban sunlight and liquid dark eyes, yet her roles in Knives Out, Blade Runner 2049, and No Time to Die reveal steely precision beneath the warmth. Her aesthetic lives in golden hour light on water, silk catching candlelight, the tension between softness and danger. Warm golds, deep blacks, and flashes of crystalline white, like champagne in a cut-crystal glass.',
	'lupita-nyong-o':
		'Lupita Nyong\'o turns every red carpet into a color field painting through sheer chromatic fearlessness. From the pale blue Prada at her first Oscar to the bold Versace metallics of Black Panther premieres, she treats fashion as an extension of performance. Her presence carries the same tightly controlled intensity she brought to 12 Years a Slave and Us; nothing is accidental, yet nothing feels labored. Saturated jewel tones, electric cobalt, molten gold, and deep violet against rich, luminous darkness.',
	'jeff-goldblum':
		'Jeff Goldblum is elegant chaos theory in motion, the strange attractor in every room he enters. His signature half-stammer, half-jazz riff delivery (perfected across Jurassic Park, The Fly, and countless late-night appearances) turns ordinary sentences into unpredictable melodic lines. He dresses like a bebop musician who wandered into a Savile Row fitting and charmed everyone into letting him improvise. Midnight navy and black punctuated by unexpected coral, deep burgundy, and the warm gleam of thick-rimmed tortoiseshell.',
	'benedict-cumberbatch':
		'Benedict Cumberbatch inhabits the uncanny valley between human warmth and something more alien, more precise. His Sherlock is a mind visualized as architecture, Doctor Strange bends reality into sacred geometry, and his Turing cracks codes the way light cracks through a prism. He makes intelligence itself feel like a superpower and loneliness feel like its cost. Deep dimensional gold, fractal amber, the electric arc of sorcery, and the infinite dark between folding planes of light.',
};
