import type { Component } from 'svelte';
import type { Shader } from '$lib/shaders';
import EventHorizon from './event-horizon.svelte';

export type ArticleComponent = Component<{ shader: Shader }>;

export interface ArticleMeta {
	title: string;
	subtitle: string;
	author: string;
	readingTime: string;
	/** Relative path under /static — generated by scripts/generate-share-image.mjs */
	shareImage: string;
}

export const articleMeta: Record<string, ArticleMeta> = {
	'event-horizon': {
		title: 'How to render a black hole',
		subtitle:
			'A real-time Schwarzschild ray tracer in under six hundred lines of WebGL. The geodesic equation, Doppler beaming, a photon ring you can actually see.',
		author: 'Paul Bakaus & Claude',
		readingTime: '20 minute read · 5 interactive sandboxes',
		shareImage: '/share/learn-event-horizon.jpg'
	}
};

export const articles: Record<string, ArticleComponent> = {
	'event-horizon': EventHorizon
};

export function hasArticle(id: string): boolean {
	return id in articles;
}
